### ISSUE TITLE
PserverSRO Getötet

### ISSUE THREAD

**Issue by Sybtek** [kokspflanze/PServerSRO#1]
installation wont work

http://www.bilder-upload.eu/show.php?file=a8636d-1458603375.png

**Comment by kokspflanze** [comment]
![composer](http://d.pr/i/cYoY.png)

tested and works for me, can you post your composer.json?

**Comment by Sybtek** [comment]
`{
  "name": "kokspflanze/pserverCMS",
  "description": "CMS for pServer",
  "keywords": [
    "framework",
    "zf2",
    "twig"
  ],
  "homepage": "https://github.com/kokspflanze/pserverCMSFull",
  "require": {
    "zendframework/Zend-developer-tools": "dev-master",
    "kokspflanze/p-server-cms": "~0.1",
    "zf-commons/zfc-twig": "dev-master",
    "mabuzagu/pdo-dblib-module": "dev-master"
  }
}
`

im using debian 8

**Comment by kokspflanze** [comment]
change it to that

```php
{
  "name": "kokspflanze/pserverCMS",
  "description": "CMS for pServer",
  "keywords": [
    "framework",
    "zf2",
    "twig"
  ],
  "homepage": "https://github.com/kokspflanze/pserverCMSFull",
  "require": {
    "zendframework/Zend-developer-tools": "dev-master",
    "kokspflanze/p-server-cms": "~0.1",
    "zf-commons/zfc-twig": "dev-master",
    "mabuzagu/pdo-dblib-module": "dev-master",
    "kokspflanze/p-server-sro": "^0.3.0"
  }
}
```

than run `php composer.phar update` again

**Comment by Sybtek** [comment]
ok thx for help. now the modul is installed... but how to activate the features? i mean that u can see the job rankings and unstuck chars....?

i allready did the all steps shown in the instruction
![screenshot_5](https://cloud.githubusercontent.com/assets/17151165/14004912/35af06e2-f15e-11e5-974f-1035cf623bc4.png)
but still wont show me job ranking on webpage

![screenshot_4](https://cloud.githubusercontent.com/assets/17151165/14004868/c2507e56-f15d-11e5-85a3-8da2005102ed.png)

is there anything more to do?

Best regards

**Comment by kokspflanze** [comment]
its a rights problem.

you have to add

https://github.com/kokspflanze/PServerSRO/blob/master/config/module.config.php#L9-L65

to this part 

https://github.com/kokspflanze/pserverCMSFull/blob/master/config/autoload/bjyauthorize.global.php#L43-L194


see also https://github.com/bjyoungblood/BjyAuthorize/blob/master/docs/simple-example.md

**Comment by great4ever** [comment]
i did what you said but it isnt working for me

**Comment by kokspflanze** [comment]
i will create a guide for it,next days

**Comment by kokspflanze** [comment]
@great4ever @crayon1337 was so nice and created a little guide https://github.com/kokspflanze/PServerSRO/pull/4/files

i will add some styles and check if smth is missing, than there should be a good basic guide for everyone =)
