### ISSUE TITLE
Fortress War (show up)

### ISSUE THREAD

**Issue by yassenes** [kokspflanze/PServerSRO#2]
Can you make the fortress wars show up as "Not occupied" instead of not showing it at all? would be hella lot better.

Also if possible, add something in config to select which fortresses to show up. Some people don't have Constantinople Fortress enabled ingame.

Thanks a lot!

**Comment by kokspflanze** [comment]
added a test-version with https://github.com/kokspflanze/PServerSRO/commit/8dd8e513702642927454be4ad5eef7d8440930bb

just add in your composer.json

```
"kokspflanze/p-server-core": "dev-master as 1.8",
"kokspflanze/game-backend": "dev-master as 0.8",
"kokspflanze/p-server-sro": "dev-master"
```

and clean the cache in `data/cache`

**Comment by kokspflanze** [comment]
is now taged =)
